// ! name and link should be same

export const projects = [
  {
    id: 4,
    title: "Event Hub",
    description:
      "Event organizing web-app where you can book tickets for events",
    imageSrc: "/images/Eventhub.png",
    imageLogo: "/images/event-hub.png",
    name: "event-hub",
    githubLink: "https://github.com/hevinkalathiya/eventify",
    liveLink: "https://eventify-two.vercel.app/",
    link: "/projects/event-hub",
    techStack: [
      "React",
      "TypeScript",
      "TailwindCSS",
      "NextJS",
      "Shadcn-UI",
      "Framer Motion",
      "NodeJS",
      "Stripe",
      "NextAuth",
      "Vercel",
    ],
  },
  {
    id: 2,
    title: "Airbnb",
    description: "Airbnb clone web-app where you can book rooms for stay",
    imageSrc: "/images/airbnb.png",
    imageLogo: "/images/airbnb-logo.png",
    name: "airbnb",
    githubLink: "https://github.com/hevinkalathiya/airbnb",
    liveLink: "https://airbnb-hevinkalathiya.vercel.app/",
    link: "/projects/airbnb",
    techStack: ["React", "TypeScript", "TailwindCSS", "NextJS"],
  },
  {
    id: 1,
    title: "Tour Managment",
    description: "Tour managment web-app where you can book tickets for tours",
    imageSrc: "/images/passport-pals.png",
    imageLogo: "/images/passport-pals-logo.png",
    name: "tour-managment",
    githubLink: "https://github.com/Jevil299/Passport-pals-frontend",
    liveLink: "https://passport-palss.vercel.app/",
    link: "/projects/tour-managment",
    techStack: ["React", "SCSS", "NodeJS"],
  },
  {
    id: 3,
    title: "Anime Search",
    description: "Anime search web-app where you can search for anime",
    imageSrc: "/images/anime-search.png",
    imageLogo: "/images/anime-search-logo.png",
    name: "anime-search",
    githubLink: "https://github.com/hevinkalathiya/Kalkani-it-task",
    liveLink: "https://kalkani-it-task1.vercel.app/",
    link: "/projects/anime-search",
    techStack: [
      "React",
      "TypeScript",
      "TailwindCSS",
      "NextJS",
      "Jikan API",
      "Shadcn-UI",
    ],
  },
];
