export const projects = [
  {
    id: 1,
    title: "Tour Managment",
    description: "This is Tour Managment App",
    imageSrc: "/images/passport-pals.png",
    name: "tour-managment",
    githubLink: "https://github.com/Jevil299/Passport-pals-frontend",
    liveLink: "https://passport-palss.vercel.app/",
    link: "/projects/tour-managment",
    techStack: ["React", "JavaScript", "SCSS", "NodeJS"],
  },
  {
    id: 2,
    title: "Airbnb",
    description: "The Ai Web-App for you to talk with your PDFs",
    imageSrc: "/images/airbnb.png",
    name: "airbnb",
    githubLink: "https://github.com/hevinkalathiya/airbnb",
    liveLink: "https://airbnb-hevinkalathiya.vercel.app/",
    link: "/projects/airbnb",
    techStack: ["React", "TypeScript", "TailwindCSS", "NextJS"],
  },
  {
    id: 3,
    title: "Anime Search",
    description: "Find your favorite anime",
    imageSrc: "/images/anime-search.png",
    name: "anime-search",
    githubLink: "https://github.com/hevinkalathiya/Kalkani-it-task",
    liveLink: "https://kalkani-it-task1.vercel.app/",
    link: "/projects/anime-search",
    techStack: [
      "React",
      "TypeScript",
      "TailwindCSS",
      "NextJS",
      "Jikan API",
      "Shadcn-UI",
    ],
  },
];
