export const techItems = [
  {
    name: "Html",
    description: "Markup Language",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    imageSrc: "/images/html.svg",
  },
  {
    name: "CSS",
    description: "Styling Language",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    imageSrc: "/images/css.svg",
  },
  {
    name: "React",
    description: "UI Library",
    url: "https://reactjs.org/",
    imageSrc: "/images/react.svg",
  },
  {
    name: "Next.js",
    description: "React Framework",
    url: "https://nextjs.org/",
    imageSrc: "/images/nextjs.svg",
  },
  {
    name: "Tailwind CSS",
    description: "Styling Library",
    url: "https://tailwindcss.com/",
    imageSrc: "/images/tailwindcss-icon.svg",
  },
  {
    name: "TypeScript",
    description: "Typed Superset of JavaScript Library",
    url: "https://www.typescriptlang.org/",
    imageSrc: "/images/typescript-icon.svg",
  },
  {
    name: "Node.js",
    description: "Backend Library",
    url: "https://nodejs.org/",
    imageSrc: "/images/node-js.svg",
  },
  {
    name: "Express.js",
    description: "Creating servers",
    url: "https://expressjs.com/",
    imageSrc: "/images/express.svg",
  },
  {
    name: "Postgres SQL",
    description: "SQL database",
    url: "https://www.mysql.com/",
    imageSrc: "/images/postgresql.svg",
  },
  {
    name: "MongoDB",
    description: "No-SQL database",
    url: "https://www.mongodb.com/",
    imageSrc: "/images/mongodb.svg",
  },
  {
    name: "Vercel",
    description: "Hosting Provider",
    url: "https://vercel.com/",
    imageSrc: "/images/vercel.svg",
  },
  {
    name: "Prisma",
    description: "interacting with databases",
    url: "https://vercel.com/",
    imageSrc: "/images/prisma.svg",
  },
  {
    name: "Redux",
    description: "State Management",
    url: "https://redux.js.org/",
    imageSrc: "/images/redux.svg",
  },
  {
    name: "Docker",
    description: "Containerization",
    url: "https://www.docker.com/",
    imageSrc: "/images/docker.svg",
  },
  {
    name: "Git",
    description: "Version Control",
    url: "https://git-scm.com/",
    imageSrc: "/images/git.svg",
  },
];
